#!usr/bin/env bash
git filter-branch --env-filter '
if [ "$GIT_AUTHOR_EMAIL" = "d.irinkov@casualino.com" ]
then
    GIT_AUTHOR_NAME="Maix31"
    GIT_AUTHOR_EMAIL="darkmitko@abv.bg"
fi
if [ "$GIT_COMMITTER_EMAIL" = "d.irinkov@casualino.com" ]
then
    GIT_COMMITTER_NAME="Maix31"
    GIT_COMMITTER_EMAIL="darkmitko@abv.bg"
fi
' --tag-name-filter cat -- --branches --tags